apiVersion: v1
kind: Pod
metadata:
  name: gvisor-demo
spec:
  runtimeClassName: gvisor
  containers:
  - name: c
    image: docker.m.daocloud.io/library/busybox:latest
    command: ["sleep", "3600"]
